-- MySQL Script generated by MySQL Workbench
-- 05/16/14 10:56:17
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DriveCommunal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DriveCommunal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `DriveCommunal` ;

-- -----------------------------------------------------
-- Table `DriveCommunal`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriveCommunal`.`User` ;

CREATE TABLE IF NOT EXISTS `DriveCommunal`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `isSeller` TINYINT(1) NOT NULL DEFAULT 0,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `displayName` VARCHAR(255) NOT NULL,
  `titleOrGender` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DriveCommunal`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriveCommunal`.`Product` ;

CREATE TABLE IF NOT EXISTS `DriveCommunal`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` DECIMAL NOT NULL,
  `quantity` INT NOT NULL,
  `description` TEXT NULL,
  `idSeller` INT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `idSeller_FK_idx` (`idSeller` ASC),
  UNIQUE INDEX `idProduct_UNIQUE` (`idProduct` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `idSeller_FK`
    FOREIGN KEY (`idSeller`)
    REFERENCES `DriveCommunal`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DriveCommunal`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriveCommunal`.`Address` ;

CREATE TABLE IF NOT EXISTS `DriveCommunal`.`Address` (
  `idAddress` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `displayName` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `zipCode` INT NOT NULL,
  `phoneNumber` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idAddress`),
  UNIQUE INDEX `idAddress_UNIQUE` (`idAddress` ASC),
  INDEX `idUser_FK_idx` (`idUser` ASC),
  CONSTRAINT `idUser_FK`
    FOREIGN KEY (`idUser`)
    REFERENCES `DriveCommunal`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
